# Site settings
show_downloads: false
title: Windup Documentation
permalink: pretty
repository: windup/windup-documentation
baseurl: /

# logo: "/assets/img/forklift-logo-darkbg.svg"
type: website
future: false

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
# defaults:
#   - scope:
#       path: "assets/img"
    # values:
    #   image: true

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# empty array for asciidoc
asciidoc: {}
# upstream doc attributes
asciidoctor:
  attributes:
  - showtitle=@
  - build=upstream
  - imagesdir=../topics/images
  - UserCLIBookName=CLI Guide
  - RulesDevBookName=Rules Development Guide
  - PluginBookName=IDE Plugin Guide
  - IntroToMTABookName=Introduction to the Migration Toolkit for Applications
  - WebConsoleBookName=Web Console Guide
  - MavenBookName=Maven Plugin Guide
  - ReleaseNotesName=Release Notes
  safe: unsafe

exclude:
  - README.adoc
  - .history
  - CONTRIBUTING.adoc
  - Gemfile.lock

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
